# Site settings
title: Solace Messaging using Apache Qpid JMS 2.0 over AMQP
summary: These tutorials get you up to speed sending and receiving messages with Solace technology.
baseurl: "/solace-samples-amqp-qpid-jms2"
repository: https://github.com/SolaceSamples/solace-samples-amqp-qpid-jms2

# Also see _includes/intro.html to customize the description which gets included in index.html.

# Config Links
links-get-started-amqp: //dev.solace.com/get-started/amqp-tutorials/
links-get-started-amqp-jms1-dev: //docs.solace.com/Configuring-and-Managing/AMQP-Tasks/Managing-AMQP-Messaging.htm
links-get-started-amqp-jms2-dev: //solace.com/samples/solace-samples-amqp-qpid-jms2/
links-get-started-amqp-jms1-cloud: //cloud.solace.com/samples/solace-samples-amqp-qpid-jms1/
links-get-started-amqp-jms2-cloud: //cloud.solace.com/samples/solace-samples-amqp-qpid-jms2/
links-get-started-jms-dev: //solace.com/samples/solace-samples-jms/
links-get-started-jms-cloud: //cloud.solace.com/samples/solace-samples-jms/
links-get-started-java-topic-to-queue-mapping: //solace.com/samples/solace-samples-java/topic-to-queue-mapping/
links-get-started-jms-topic-to-queue-mapping: //dev.solace.com/get-started/jms-tutorials/topic-queue-mapping_jms/
links-community: //solace.community
links-downloads: //solace.com/downloads/
links-tech-other: //solace.com/products/tech/
links-jms1-specification: //download.oracle.com/otndocs/jcp/7195-jms-1.1-fr-spec-oth-JSpec/
links-jms2-specification: //download.oracle.com/otndocs/jcp/jms-2_0-fr-spec/
links-solaceCloud-setup: //https://solace.com/cloud/
docs-core-concepts: //docs.solace.com/PubSub-Basics/Core-Concepts.htm
docs-management-tools: //docs.solace.com/Management-Tools.htm
docs-management-soladmin: //docs.solace.com/SolAdmin/SolAdmin-Overview.htm?Highlight=SolAdmin
docs-management-cli: //docs.solace.com/Solace-CLI/Using-Solace-CLI.htm
docs-topic-mapping: //docs.solace.com/PubSub-Basics/Core-Concepts.htm
docs-semp: //docs.solace.com/SEMP/Using-Legacy-SEMP.htm
docs-semp-get-started: //docs.solace.com/SEMP/SEMP-Get-Started.htm
docs-confugure-queues: //docs.solace.com/Configuring-and-Managing/Configuring-Queues.htm
